name: app1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Testing ----------------------------
  messaging_testing:
    path: ../messaging_testing

  notification_testing:
    path: ../notification_testing


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  built_value_generator: ^8.4.0
  http: ^0.12.0
  url_launcher: 6.0.0

flutter:
  uses-material-design: true
